4 implement text fields, charts, popup modal, tooltips, logos and editor design
bluewave-labs/bluewave-hrm pull request #20
Opened 2024-05-31 03:12 UTC by ergunesra

4 implement text fields, charts, popup modal, tooltips, logos and editor design

2024-06-18 23:55 UTC, zaidi201 approved these changes

2024-06-18 23:57 UTC, zaidi201 requested changes
some of your files are conflicting with main branch.

2024-06-19 02:21 UTC, ergunesra commented
I merged some components from the main branch, these caused the conflict. I will remove the folders.

2024-06-22 19:33 UTC, closed without merging

2024-06-22 19:33 UTC, ergunesra commented
practice