5 implement progress announcements sidebar popup messages file upload dialog
bluewave-labs/bluewave-hrm pull request #54
Opened 2024-07-16 20:32 UTC by sejunpark2002

2024-07-19 19:21 UTC, zaidi201 approved these changes, later dismissed

2024-07-19 19:22 UTC, zaidi201 commented
Please resolve the conflicts then I will merge the code. if you need assistance do let me know

2024-07-24 12:55 UTC, zaidi201 submitted a review, later dismissed

2024-08-04 20:20 UTC, zaidi201 submitted a review, later dismissed

2024-08-04 20:20 UTC, zaidi201 commented
There are conflicts in the file please resolve it

2024-08-27 21:05 UTC, zaidi201 approved these changes

2024-08-27 21:06 UTC, zaidi201 commented
You have multiple conflicts in the file. Please resolve it and sending you some code suggestions as well

2024-08-27 21:07 UTC, zaidi201 requested changes
Have multiple conflicts in the file. Please resolve it and sending you some code suggestions as well

2024-11-02 01:16 UTC, gorkem-bwl commented
What is the latest status here @sejunpark2002 ?

2025-02-07 21:27 UTC, closed without merging