backend code for time off
bluewave-labs/bluewave-hrm pull request #61
Opened 2024-08-01 12:41 UTC by shidrath

2024-08-01 12:42 UTC, shidrath commented
added the backend time off logic

2024-08-04 20:16 UTC, zaidi201 requested changes
I cannot see any files changes in this pull request. Let me know if you need help in committing code

2024-08-12 20:26 UTC, zaidi201 approved these changes

2024-08-12 20:27 UTC, zaidi201 requested changes
changes should be pushed to dev-backend branch, not in the main

2024-08-14 13:45 UTC, closed without merging